### ISSUE TITLE
scaling the topaz directory

### ISSUE THREAD

**Issue by tanmaykm** [aserto-dev/topaz#135] opened 2023-09-26 08:28 UTC
I am just starting to evaluate Topaz, and this is more of a question.

Our application can have a lot of users and entities on which we need to evaluate permissions. On a large installation, we can have entity counts of the order of a few million. Is it a fair to expect to be able to represent all of those in the topaz directory? Not with all their attributes, but with a subset of attributes that we rant to use in the policies - maybe around 5 per entity. We will have relations also, and those will be of similar order.

In my trials I am finding importing the entities from a dump slowing down to a crawl after around 200K entries, not finishing even after tens of minutes, which is something that won't work for us. E.g. the shell command to import where I had to interrupt it after some time as it was going too slow and there were a total of 2M to be imported:
```
$ time topaz import -i -d .
>>> importing data from .
      relations: 393560^C

real	6m28.189s
user	0m10.259s
sys	0m2.223s
```

I may be doing things in a way that's not recommended. Is there any other way to do it?

Or am I trying something that the internal directory is not meant for? What is the recommended architecture in such cases where we need to evaluate policies across a large set of entities?

Thanks in advance!

**Comment by gertd** [comment] 2023-09-27 00:55
@ tanmaykm This is caused by the fact that the importer service currently does not correctly chunk the stream, hence it becomes one huge transaction that needs to be de-spooled. I will create a fix to address this.

Testing loading 160K users into an empty directory without the fix:

```
> time topaz import -d data --insecure
>>> importing data from data
   object types skipped
    permissions skipped
 relation types skipped
        objects 163539
      relations skipped
topaz import -d data --insecure  

4.37s user 1.66s system 5% cpu 1:47.82 total
```

With batching turned on:

```
> time topaz import -d data --insecure --no-check
>>> importing data from data
   object types skipped
    permissions skipped
 relation types skipped
        objects 163539
      relations skipped
topaz import -d data --insecure --no-check  

1.98s user 1.19s system 26% cpu 12.047 total
```

**Comment by tanmaykm** [comment] 2023-09-27 11:12
Thanks for looking into it, and the swift response!

**Comment by ogazitt** [comment] 2023-10-27 21:23
Hi @tanmaykm, were you able to evaluate the fix?  Did it address the timing issue you were seeing?

**Comment by gertd** [comment] 2023-12-23 00:59
Closing this issue, no data or feedback received.

**Closed by gertd** 2023-12-23 00:59 UTC
Labels: question
